feat: test & doc support

diff --git a/.github/workflows/release-packaging.yml b/.github/workflows/release-packaging.yml
--- a/.github/workflows/release-packaging.yml
+++ b/.github/workflows/release-packaging.yml
@@ -19,18 +19,55 @@ jobs:
       - name: Load dotenv
         run: just ci-load-dotenv
 
+      # Retry multiple times, sometimes in CI, gdlint raise "file exists"
       - name: Check
-        run: just fmt
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 1
+          max_attempts: 3
+          command: just fmt
 
       - name: Ensure version is equal to tag
         if: startsWith(github.ref, 'refs/tags/')
         run: |
-          [ "${{ env.game_version }}" == "${{ env.BRANCH_NAME }}" ] || exit 2
+          [ "${{ env.addon_version }}" == "${{ env.BRANCH_NAME }}" ] || exit 2
+
+  test:
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 30
+
+    strategy:
+      fail-fast: true
+      matrix:
+        os: [ ubuntu-22.04, windows-2022, macos-12 ]
+        godot_version: [ '4.0.4', '4.1.3', '4.2.1' ]
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: extractions/setup-just@v1
+
+      - name: Setup Godot dependencies
+        uses: ./.github/actions/setup-godot
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+
+      - name: Run unit tests
+        run: just unit
+        env:
+          GODOT_VERSION: ${{ matrix.godot_version }}
+
+      - name: Run integration tests
+        if: ${{ runner.os == 'Linux' }}
+        run: just integration
+        env:
+          GODOT_VERSION: ${{ matrix.godot_version }}
 
   publish:
     runs-on: ubuntu-22.04
     timeout-minutes: 30
-    needs: [check]
+    needs: [check, test]
 
     if: startsWith(github.ref, 'refs/tags/')
 
